/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as ContactDetailsIndexRouteImport } from './routes/contact-details/index'
import { Route as HelpCenterLayoutRouteImport } from './routes/help-center/_layout'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as ProtectedUserIndexRouteImport } from './routes/protected/user/index'
import { Route as HelpCenterLayoutIndexRouteImport } from './routes/help-center/_layout/index'
import { Route as CategoriesCategoryIdIndexRouteImport } from './routes/categories/$categoryId/index'
import { Route as CategoriesCategoryIdArticleIdRouteImport } from './routes/categories/$categoryId/$articleId'
import { Route as HelpCenterLayoutSubmit_requestIndexRouteImport } from './routes/help-center/_layout/submit_request/index'
import { Route as HelpCenterLayoutTopic_sectionLayoutRouteImport } from './routes/help-center/_layout/topic_section/_layout'
import { Route as HelpCenterLayoutTopic_categoryLayoutRouteImport } from './routes/help-center/_layout/topic_category/_layout'
import { Route as HelpCenterLayoutTopic_articleLayoutRouteImport } from './routes/help-center/_layout/topic_article/_layout'
import { Route as HelpCenterLayoutActivitiesLayoutRouteImport } from './routes/help-center/_layout/activities/_layout'
import { Route as HelpCenterLayoutTopic_sectionLayoutIndexRouteImport } from './routes/help-center/_layout/topic_section/_layout/index'
import { Route as HelpCenterLayoutTopic_categoryLayoutIndexRouteImport } from './routes/help-center/_layout/topic_category/_layout/index'
import { Route as HelpCenterLayoutTopic_articleLayoutIndexRouteImport } from './routes/help-center/_layout/topic_article/_layout/index'
import { Route as HelpCenterLayoutTopic_sectionLayoutSlugRouteImport } from './routes/help-center/_layout/topic_section/_layout/$slug'
import { Route as HelpCenterLayoutTopic_categoryLayoutSlugRouteImport } from './routes/help-center/_layout/topic_category/_layout/$slug'
import { Route as HelpCenterLayoutTopic_articleLayoutSlugRouteImport } from './routes/help-center/_layout/topic_article/_layout/$slug'
import { Route as HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRouteImport } from './routes/help-center/_layout/activities/_layout/subscriptions/index'
import { Route as HelpCenterLayoutActivitiesLayoutCommentsIndexRouteImport } from './routes/help-center/_layout/activities/_layout/comments/index'

const authSigninLazyRouteImport = createFileRoute('/(auth)/signin')()
const authSignUpLazyRouteImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyRouteImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyRouteImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const HelpCenterLayoutTopic_sectionRouteImport = createFileRoute(
  '/help-center/_layout/topic_section',
)()
const HelpCenterLayoutTopic_categoryRouteImport = createFileRoute(
  '/help-center/_layout/topic_category',
)()
const HelpCenterLayoutTopic_articleRouteImport = createFileRoute(
  '/help-center/_layout/topic_article',
)()
const HelpCenterLayoutActivitiesRouteImport = createFileRoute(
  '/help-center/_layout/activities',
)()

const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactDetailsIndexRoute = ContactDetailsIndexRouteImport.update({
  id: '/contact-details/',
  path: '/contact-details/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninLazyRoute = authSigninLazyRouteImport
  .update({
    id: '/(auth)/signin',
    path: '/signin',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/signin.lazy').then((d) => d.Route))
const authSignUpLazyRoute = authSignUpLazyRouteImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))
const authSignIn2LazyRoute = authSignIn2LazyRouteImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))
const authForgotPasswordLazyRoute = authForgotPasswordLazyRouteImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )
const HelpCenterLayoutRoute = HelpCenterLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => HelpCenterRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterLayoutTopic_sectionRoute =
  HelpCenterLayoutTopic_sectionRouteImport.update({
    id: '/topic_section',
    path: '/topic_section',
    getParentRoute: () => HelpCenterLayoutRoute,
  } as any)
const HelpCenterLayoutTopic_categoryRoute =
  HelpCenterLayoutTopic_categoryRouteImport.update({
    id: '/topic_category',
    path: '/topic_category',
    getParentRoute: () => HelpCenterLayoutRoute,
  } as any)
const HelpCenterLayoutTopic_articleRoute =
  HelpCenterLayoutTopic_articleRouteImport.update({
    id: '/topic_article',
    path: '/topic_article',
    getParentRoute: () => HelpCenterLayoutRoute,
  } as any)
const HelpCenterLayoutActivitiesRoute =
  HelpCenterLayoutActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => HelpCenterLayoutRoute,
  } as any)
const ProtectedUserIndexRoute = ProtectedUserIndexRouteImport.update({
  id: '/protected/user/',
  path: '/protected/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterLayoutIndexRoute = HelpCenterLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpCenterLayoutRoute,
} as any)
const CategoriesCategoryIdIndexRoute =
  CategoriesCategoryIdIndexRouteImport.update({
    id: '/categories/$categoryId/',
    path: '/categories/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesCategoryIdArticleIdRoute =
  CategoriesCategoryIdArticleIdRouteImport.update({
    id: '/categories/$categoryId/$articleId',
    path: '/categories/$categoryId/$articleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HelpCenterLayoutSubmit_requestIndexRoute =
  HelpCenterLayoutSubmit_requestIndexRouteImport.update({
    id: '/submit_request/',
    path: '/submit_request/',
    getParentRoute: () => HelpCenterLayoutRoute,
  } as any)
const HelpCenterLayoutTopic_sectionLayoutRoute =
  HelpCenterLayoutTopic_sectionLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => HelpCenterLayoutTopic_sectionRoute,
  } as any)
const HelpCenterLayoutTopic_categoryLayoutRoute =
  HelpCenterLayoutTopic_categoryLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => HelpCenterLayoutTopic_categoryRoute,
  } as any)
const HelpCenterLayoutTopic_articleLayoutRoute =
  HelpCenterLayoutTopic_articleLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => HelpCenterLayoutTopic_articleRoute,
  } as any)
const HelpCenterLayoutActivitiesLayoutRoute =
  HelpCenterLayoutActivitiesLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => HelpCenterLayoutActivitiesRoute,
  } as any)
const HelpCenterLayoutTopic_sectionLayoutIndexRoute =
  HelpCenterLayoutTopic_sectionLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HelpCenterLayoutTopic_sectionLayoutRoute,
  } as any)
const HelpCenterLayoutTopic_categoryLayoutIndexRoute =
  HelpCenterLayoutTopic_categoryLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HelpCenterLayoutTopic_categoryLayoutRoute,
  } as any)
const HelpCenterLayoutTopic_articleLayoutIndexRoute =
  HelpCenterLayoutTopic_articleLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HelpCenterLayoutTopic_articleLayoutRoute,
  } as any)
const HelpCenterLayoutTopic_sectionLayoutSlugRoute =
  HelpCenterLayoutTopic_sectionLayoutSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => HelpCenterLayoutTopic_sectionLayoutRoute,
  } as any)
const HelpCenterLayoutTopic_categoryLayoutSlugRoute =
  HelpCenterLayoutTopic_categoryLayoutSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => HelpCenterLayoutTopic_categoryLayoutRoute,
  } as any)
const HelpCenterLayoutTopic_articleLayoutSlugRoute =
  HelpCenterLayoutTopic_articleLayoutSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => HelpCenterLayoutTopic_articleLayoutRoute,
  } as any)
const HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRoute =
  HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => HelpCenterLayoutActivitiesLayoutRoute,
  } as any)
const HelpCenterLayoutActivitiesLayoutCommentsIndexRoute =
  HelpCenterLayoutActivitiesLayoutCommentsIndexRouteImport.update({
    id: '/comments/',
    path: '/comments/',
    getParentRoute: () => HelpCenterLayoutActivitiesLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help-center': typeof HelpCenterLayoutRouteWithChildren
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/signin': typeof authSigninLazyRoute
  '/contact-details': typeof ContactDetailsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/categories/$categoryId/$articleId': typeof CategoriesCategoryIdArticleIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdIndexRoute
  '/help-center/': typeof HelpCenterLayoutIndexRoute
  '/protected/user': typeof ProtectedUserIndexRoute
  '/help-center/activities': typeof HelpCenterLayoutActivitiesLayoutRouteWithChildren
  '/help-center/topic_article': typeof HelpCenterLayoutTopic_articleLayoutRouteWithChildren
  '/help-center/topic_category': typeof HelpCenterLayoutTopic_categoryLayoutRouteWithChildren
  '/help-center/topic_section': typeof HelpCenterLayoutTopic_sectionLayoutRouteWithChildren
  '/help-center/submit_request': typeof HelpCenterLayoutSubmit_requestIndexRoute
  '/help-center/topic_article/$slug': typeof HelpCenterLayoutTopic_articleLayoutSlugRoute
  '/help-center/topic_category/$slug': typeof HelpCenterLayoutTopic_categoryLayoutSlugRoute
  '/help-center/topic_section/$slug': typeof HelpCenterLayoutTopic_sectionLayoutSlugRoute
  '/help-center/topic_article/': typeof HelpCenterLayoutTopic_articleLayoutIndexRoute
  '/help-center/topic_category/': typeof HelpCenterLayoutTopic_categoryLayoutIndexRoute
  '/help-center/topic_section/': typeof HelpCenterLayoutTopic_sectionLayoutIndexRoute
  '/help-center/activities/comments': typeof HelpCenterLayoutActivitiesLayoutCommentsIndexRoute
  '/help-center/activities/subscriptions': typeof HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help-center': typeof HelpCenterLayoutIndexRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/signin': typeof authSigninLazyRoute
  '/contact-details': typeof ContactDetailsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/categories/$categoryId/$articleId': typeof CategoriesCategoryIdArticleIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdIndexRoute
  '/protected/user': typeof ProtectedUserIndexRoute
  '/help-center/activities': typeof HelpCenterLayoutActivitiesLayoutRouteWithChildren
  '/help-center/topic_article': typeof HelpCenterLayoutTopic_articleLayoutIndexRoute
  '/help-center/topic_category': typeof HelpCenterLayoutTopic_categoryLayoutIndexRoute
  '/help-center/topic_section': typeof HelpCenterLayoutTopic_sectionLayoutIndexRoute
  '/help-center/submit_request': typeof HelpCenterLayoutSubmit_requestIndexRoute
  '/help-center/topic_article/$slug': typeof HelpCenterLayoutTopic_articleLayoutSlugRoute
  '/help-center/topic_category/$slug': typeof HelpCenterLayoutTopic_categoryLayoutSlugRoute
  '/help-center/topic_section/$slug': typeof HelpCenterLayoutTopic_sectionLayoutSlugRoute
  '/help-center/activities/comments': typeof HelpCenterLayoutActivitiesLayoutCommentsIndexRoute
  '/help-center/activities/subscriptions': typeof HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help-center': typeof HelpCenterRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/help-center/_layout': typeof HelpCenterLayoutRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(auth)/signin': typeof authSigninLazyRoute
  '/contact-details/': typeof ContactDetailsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/categories/$categoryId/$articleId': typeof CategoriesCategoryIdArticleIdRoute
  '/categories/$categoryId/': typeof CategoriesCategoryIdIndexRoute
  '/help-center/_layout/': typeof HelpCenterLayoutIndexRoute
  '/protected/user/': typeof ProtectedUserIndexRoute
  '/help-center/_layout/activities': typeof HelpCenterLayoutActivitiesRouteWithChildren
  '/help-center/_layout/activities/_layout': typeof HelpCenterLayoutActivitiesLayoutRouteWithChildren
  '/help-center/_layout/topic_article': typeof HelpCenterLayoutTopic_articleRouteWithChildren
  '/help-center/_layout/topic_article/_layout': typeof HelpCenterLayoutTopic_articleLayoutRouteWithChildren
  '/help-center/_layout/topic_category': typeof HelpCenterLayoutTopic_categoryRouteWithChildren
  '/help-center/_layout/topic_category/_layout': typeof HelpCenterLayoutTopic_categoryLayoutRouteWithChildren
  '/help-center/_layout/topic_section': typeof HelpCenterLayoutTopic_sectionRouteWithChildren
  '/help-center/_layout/topic_section/_layout': typeof HelpCenterLayoutTopic_sectionLayoutRouteWithChildren
  '/help-center/_layout/submit_request/': typeof HelpCenterLayoutSubmit_requestIndexRoute
  '/help-center/_layout/topic_article/_layout/$slug': typeof HelpCenterLayoutTopic_articleLayoutSlugRoute
  '/help-center/_layout/topic_category/_layout/$slug': typeof HelpCenterLayoutTopic_categoryLayoutSlugRoute
  '/help-center/_layout/topic_section/_layout/$slug': typeof HelpCenterLayoutTopic_sectionLayoutSlugRoute
  '/help-center/_layout/topic_article/_layout/': typeof HelpCenterLayoutTopic_articleLayoutIndexRoute
  '/help-center/_layout/topic_category/_layout/': typeof HelpCenterLayoutTopic_categoryLayoutIndexRoute
  '/help-center/_layout/topic_section/_layout/': typeof HelpCenterLayoutTopic_sectionLayoutIndexRoute
  '/help-center/_layout/activities/_layout/comments/': typeof HelpCenterLayoutActivitiesLayoutCommentsIndexRoute
  '/help-center/_layout/activities/_layout/subscriptions/': typeof HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help-center'
    | '/otp'
    | '/sign-in'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/signin'
    | '/contact-details'
    | '/requests'
    | '/categories/$categoryId/$articleId'
    | '/categories/$categoryId'
    | '/help-center/'
    | '/protected/user'
    | '/help-center/activities'
    | '/help-center/topic_article'
    | '/help-center/topic_category'
    | '/help-center/topic_section'
    | '/help-center/submit_request'
    | '/help-center/topic_article/$slug'
    | '/help-center/topic_category/$slug'
    | '/help-center/topic_section/$slug'
    | '/help-center/topic_article/'
    | '/help-center/topic_category/'
    | '/help-center/topic_section/'
    | '/help-center/activities/comments'
    | '/help-center/activities/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help-center'
    | '/otp'
    | '/sign-in'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/signin'
    | '/contact-details'
    | '/requests'
    | '/categories/$categoryId/$articleId'
    | '/categories/$categoryId'
    | '/protected/user'
    | '/help-center/activities'
    | '/help-center/topic_article'
    | '/help-center/topic_category'
    | '/help-center/topic_section'
    | '/help-center/submit_request'
    | '/help-center/topic_article/$slug'
    | '/help-center/topic_category/$slug'
    | '/help-center/topic_section/$slug'
    | '/help-center/activities/comments'
    | '/help-center/activities/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/help-center'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/help-center/_layout'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/signin'
    | '/contact-details/'
    | '/requests/'
    | '/categories/$categoryId/$articleId'
    | '/categories/$categoryId/'
    | '/help-center/_layout/'
    | '/protected/user/'
    | '/help-center/_layout/activities'
    | '/help-center/_layout/activities/_layout'
    | '/help-center/_layout/topic_article'
    | '/help-center/_layout/topic_article/_layout'
    | '/help-center/_layout/topic_category'
    | '/help-center/_layout/topic_category/_layout'
    | '/help-center/_layout/topic_section'
    | '/help-center/_layout/topic_section/_layout'
    | '/help-center/_layout/submit_request/'
    | '/help-center/_layout/topic_article/_layout/$slug'
    | '/help-center/_layout/topic_category/_layout/$slug'
    | '/help-center/_layout/topic_section/_layout/$slug'
    | '/help-center/_layout/topic_article/_layout/'
    | '/help-center/_layout/topic_category/_layout/'
    | '/help-center/_layout/topic_section/_layout/'
    | '/help-center/_layout/activities/_layout/comments/'
    | '/help-center/_layout/activities/_layout/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpCenterRoute: typeof HelpCenterRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  authSigninLazyRoute: typeof authSigninLazyRoute
  ContactDetailsIndexRoute: typeof ContactDetailsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  CategoriesCategoryIdArticleIdRoute: typeof CategoriesCategoryIdArticleIdRoute
  CategoriesCategoryIdIndexRoute: typeof CategoriesCategoryIdIndexRoute
  ProtectedUserIndexRoute: typeof ProtectedUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-details/': {
      id: '/contact-details/'
      path: '/contact-details'
      fullPath: '/contact-details'
      preLoaderRoute: typeof ContactDetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center/_layout': {
      id: '/help-center/_layout'
      path: ''
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterLayoutRouteImport
      parentRoute: typeof HelpCenterRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center/_layout/topic_section': {
      id: '/help-center/_layout/topic_section'
      path: '/topic_section'
      fullPath: '/help-center/topic_section'
      preLoaderRoute: typeof HelpCenterLayoutTopic_sectionRouteImport
      parentRoute: typeof HelpCenterLayoutRoute
    }
    '/help-center/_layout/topic_category': {
      id: '/help-center/_layout/topic_category'
      path: '/topic_category'
      fullPath: '/help-center/topic_category'
      preLoaderRoute: typeof HelpCenterLayoutTopic_categoryRouteImport
      parentRoute: typeof HelpCenterLayoutRoute
    }
    '/help-center/_layout/topic_article': {
      id: '/help-center/_layout/topic_article'
      path: '/topic_article'
      fullPath: '/help-center/topic_article'
      preLoaderRoute: typeof HelpCenterLayoutTopic_articleRouteImport
      parentRoute: typeof HelpCenterLayoutRoute
    }
    '/help-center/_layout/activities': {
      id: '/help-center/_layout/activities'
      path: '/activities'
      fullPath: '/help-center/activities'
      preLoaderRoute: typeof HelpCenterLayoutActivitiesRouteImport
      parentRoute: typeof HelpCenterLayoutRoute
    }
    '/protected/user/': {
      id: '/protected/user/'
      path: '/protected/user'
      fullPath: '/protected/user'
      preLoaderRoute: typeof ProtectedUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center/_layout/': {
      id: '/help-center/_layout/'
      path: '/'
      fullPath: '/help-center/'
      preLoaderRoute: typeof HelpCenterLayoutIndexRouteImport
      parentRoute: typeof HelpCenterLayoutRoute
    }
    '/categories/$categoryId/': {
      id: '/categories/$categoryId/'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/$articleId': {
      id: '/categories/$categoryId/$articleId'
      path: '/categories/$categoryId/$articleId'
      fullPath: '/categories/$categoryId/$articleId'
      preLoaderRoute: typeof CategoriesCategoryIdArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center/_layout/submit_request/': {
      id: '/help-center/_layout/submit_request/'
      path: '/submit_request'
      fullPath: '/help-center/submit_request'
      preLoaderRoute: typeof HelpCenterLayoutSubmit_requestIndexRouteImport
      parentRoute: typeof HelpCenterLayoutRoute
    }
    '/help-center/_layout/topic_section/_layout': {
      id: '/help-center/_layout/topic_section/_layout'
      path: '/topic_section'
      fullPath: '/help-center/topic_section'
      preLoaderRoute: typeof HelpCenterLayoutTopic_sectionLayoutRouteImport
      parentRoute: typeof HelpCenterLayoutTopic_sectionRoute
    }
    '/help-center/_layout/topic_category/_layout': {
      id: '/help-center/_layout/topic_category/_layout'
      path: '/topic_category'
      fullPath: '/help-center/topic_category'
      preLoaderRoute: typeof HelpCenterLayoutTopic_categoryLayoutRouteImport
      parentRoute: typeof HelpCenterLayoutTopic_categoryRoute
    }
    '/help-center/_layout/topic_article/_layout': {
      id: '/help-center/_layout/topic_article/_layout'
      path: '/topic_article'
      fullPath: '/help-center/topic_article'
      preLoaderRoute: typeof HelpCenterLayoutTopic_articleLayoutRouteImport
      parentRoute: typeof HelpCenterLayoutTopic_articleRoute
    }
    '/help-center/_layout/activities/_layout': {
      id: '/help-center/_layout/activities/_layout'
      path: '/activities'
      fullPath: '/help-center/activities'
      preLoaderRoute: typeof HelpCenterLayoutActivitiesLayoutRouteImport
      parentRoute: typeof HelpCenterLayoutActivitiesRoute
    }
    '/help-center/_layout/topic_section/_layout/': {
      id: '/help-center/_layout/topic_section/_layout/'
      path: '/'
      fullPath: '/help-center/topic_section/'
      preLoaderRoute: typeof HelpCenterLayoutTopic_sectionLayoutIndexRouteImport
      parentRoute: typeof HelpCenterLayoutTopic_sectionLayoutRoute
    }
    '/help-center/_layout/topic_category/_layout/': {
      id: '/help-center/_layout/topic_category/_layout/'
      path: '/'
      fullPath: '/help-center/topic_category/'
      preLoaderRoute: typeof HelpCenterLayoutTopic_categoryLayoutIndexRouteImport
      parentRoute: typeof HelpCenterLayoutTopic_categoryLayoutRoute
    }
    '/help-center/_layout/topic_article/_layout/': {
      id: '/help-center/_layout/topic_article/_layout/'
      path: '/'
      fullPath: '/help-center/topic_article/'
      preLoaderRoute: typeof HelpCenterLayoutTopic_articleLayoutIndexRouteImport
      parentRoute: typeof HelpCenterLayoutTopic_articleLayoutRoute
    }
    '/help-center/_layout/topic_section/_layout/$slug': {
      id: '/help-center/_layout/topic_section/_layout/$slug'
      path: '/$slug'
      fullPath: '/help-center/topic_section/$slug'
      preLoaderRoute: typeof HelpCenterLayoutTopic_sectionLayoutSlugRouteImport
      parentRoute: typeof HelpCenterLayoutTopic_sectionLayoutRoute
    }
    '/help-center/_layout/topic_category/_layout/$slug': {
      id: '/help-center/_layout/topic_category/_layout/$slug'
      path: '/$slug'
      fullPath: '/help-center/topic_category/$slug'
      preLoaderRoute: typeof HelpCenterLayoutTopic_categoryLayoutSlugRouteImport
      parentRoute: typeof HelpCenterLayoutTopic_categoryLayoutRoute
    }
    '/help-center/_layout/topic_article/_layout/$slug': {
      id: '/help-center/_layout/topic_article/_layout/$slug'
      path: '/$slug'
      fullPath: '/help-center/topic_article/$slug'
      preLoaderRoute: typeof HelpCenterLayoutTopic_articleLayoutSlugRouteImport
      parentRoute: typeof HelpCenterLayoutTopic_articleLayoutRoute
    }
    '/help-center/_layout/activities/_layout/subscriptions/': {
      id: '/help-center/_layout/activities/_layout/subscriptions/'
      path: '/subscriptions'
      fullPath: '/help-center/activities/subscriptions'
      preLoaderRoute: typeof HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRouteImport
      parentRoute: typeof HelpCenterLayoutActivitiesLayoutRoute
    }
    '/help-center/_layout/activities/_layout/comments/': {
      id: '/help-center/_layout/activities/_layout/comments/'
      path: '/comments'
      fullPath: '/help-center/activities/comments'
      preLoaderRoute: typeof HelpCenterLayoutActivitiesLayoutCommentsIndexRouteImport
      parentRoute: typeof HelpCenterLayoutActivitiesLayoutRoute
    }
  }
}

interface HelpCenterLayoutActivitiesLayoutRouteChildren {
  HelpCenterLayoutActivitiesLayoutCommentsIndexRoute: typeof HelpCenterLayoutActivitiesLayoutCommentsIndexRoute
  HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRoute: typeof HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRoute
}

const HelpCenterLayoutActivitiesLayoutRouteChildren: HelpCenterLayoutActivitiesLayoutRouteChildren =
  {
    HelpCenterLayoutActivitiesLayoutCommentsIndexRoute:
      HelpCenterLayoutActivitiesLayoutCommentsIndexRoute,
    HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRoute:
      HelpCenterLayoutActivitiesLayoutSubscriptionsIndexRoute,
  }

const HelpCenterLayoutActivitiesLayoutRouteWithChildren =
  HelpCenterLayoutActivitiesLayoutRoute._addFileChildren(
    HelpCenterLayoutActivitiesLayoutRouteChildren,
  )

interface HelpCenterLayoutActivitiesRouteChildren {
  HelpCenterLayoutActivitiesLayoutRoute: typeof HelpCenterLayoutActivitiesLayoutRouteWithChildren
}

const HelpCenterLayoutActivitiesRouteChildren: HelpCenterLayoutActivitiesRouteChildren =
  {
    HelpCenterLayoutActivitiesLayoutRoute:
      HelpCenterLayoutActivitiesLayoutRouteWithChildren,
  }

const HelpCenterLayoutActivitiesRouteWithChildren =
  HelpCenterLayoutActivitiesRoute._addFileChildren(
    HelpCenterLayoutActivitiesRouteChildren,
  )

interface HelpCenterLayoutTopic_articleLayoutRouteChildren {
  HelpCenterLayoutTopic_articleLayoutSlugRoute: typeof HelpCenterLayoutTopic_articleLayoutSlugRoute
  HelpCenterLayoutTopic_articleLayoutIndexRoute: typeof HelpCenterLayoutTopic_articleLayoutIndexRoute
}

const HelpCenterLayoutTopic_articleLayoutRouteChildren: HelpCenterLayoutTopic_articleLayoutRouteChildren =
  {
    HelpCenterLayoutTopic_articleLayoutSlugRoute:
      HelpCenterLayoutTopic_articleLayoutSlugRoute,
    HelpCenterLayoutTopic_articleLayoutIndexRoute:
      HelpCenterLayoutTopic_articleLayoutIndexRoute,
  }

const HelpCenterLayoutTopic_articleLayoutRouteWithChildren =
  HelpCenterLayoutTopic_articleLayoutRoute._addFileChildren(
    HelpCenterLayoutTopic_articleLayoutRouteChildren,
  )

interface HelpCenterLayoutTopic_articleRouteChildren {
  HelpCenterLayoutTopic_articleLayoutRoute: typeof HelpCenterLayoutTopic_articleLayoutRouteWithChildren
}

const HelpCenterLayoutTopic_articleRouteChildren: HelpCenterLayoutTopic_articleRouteChildren =
  {
    HelpCenterLayoutTopic_articleLayoutRoute:
      HelpCenterLayoutTopic_articleLayoutRouteWithChildren,
  }

const HelpCenterLayoutTopic_articleRouteWithChildren =
  HelpCenterLayoutTopic_articleRoute._addFileChildren(
    HelpCenterLayoutTopic_articleRouteChildren,
  )

interface HelpCenterLayoutTopic_categoryLayoutRouteChildren {
  HelpCenterLayoutTopic_categoryLayoutSlugRoute: typeof HelpCenterLayoutTopic_categoryLayoutSlugRoute
  HelpCenterLayoutTopic_categoryLayoutIndexRoute: typeof HelpCenterLayoutTopic_categoryLayoutIndexRoute
}

const HelpCenterLayoutTopic_categoryLayoutRouteChildren: HelpCenterLayoutTopic_categoryLayoutRouteChildren =
  {
    HelpCenterLayoutTopic_categoryLayoutSlugRoute:
      HelpCenterLayoutTopic_categoryLayoutSlugRoute,
    HelpCenterLayoutTopic_categoryLayoutIndexRoute:
      HelpCenterLayoutTopic_categoryLayoutIndexRoute,
  }

const HelpCenterLayoutTopic_categoryLayoutRouteWithChildren =
  HelpCenterLayoutTopic_categoryLayoutRoute._addFileChildren(
    HelpCenterLayoutTopic_categoryLayoutRouteChildren,
  )

interface HelpCenterLayoutTopic_categoryRouteChildren {
  HelpCenterLayoutTopic_categoryLayoutRoute: typeof HelpCenterLayoutTopic_categoryLayoutRouteWithChildren
}

const HelpCenterLayoutTopic_categoryRouteChildren: HelpCenterLayoutTopic_categoryRouteChildren =
  {
    HelpCenterLayoutTopic_categoryLayoutRoute:
      HelpCenterLayoutTopic_categoryLayoutRouteWithChildren,
  }

const HelpCenterLayoutTopic_categoryRouteWithChildren =
  HelpCenterLayoutTopic_categoryRoute._addFileChildren(
    HelpCenterLayoutTopic_categoryRouteChildren,
  )

interface HelpCenterLayoutTopic_sectionLayoutRouteChildren {
  HelpCenterLayoutTopic_sectionLayoutSlugRoute: typeof HelpCenterLayoutTopic_sectionLayoutSlugRoute
  HelpCenterLayoutTopic_sectionLayoutIndexRoute: typeof HelpCenterLayoutTopic_sectionLayoutIndexRoute
}

const HelpCenterLayoutTopic_sectionLayoutRouteChildren: HelpCenterLayoutTopic_sectionLayoutRouteChildren =
  {
    HelpCenterLayoutTopic_sectionLayoutSlugRoute:
      HelpCenterLayoutTopic_sectionLayoutSlugRoute,
    HelpCenterLayoutTopic_sectionLayoutIndexRoute:
      HelpCenterLayoutTopic_sectionLayoutIndexRoute,
  }

const HelpCenterLayoutTopic_sectionLayoutRouteWithChildren =
  HelpCenterLayoutTopic_sectionLayoutRoute._addFileChildren(
    HelpCenterLayoutTopic_sectionLayoutRouteChildren,
  )

interface HelpCenterLayoutTopic_sectionRouteChildren {
  HelpCenterLayoutTopic_sectionLayoutRoute: typeof HelpCenterLayoutTopic_sectionLayoutRouteWithChildren
}

const HelpCenterLayoutTopic_sectionRouteChildren: HelpCenterLayoutTopic_sectionRouteChildren =
  {
    HelpCenterLayoutTopic_sectionLayoutRoute:
      HelpCenterLayoutTopic_sectionLayoutRouteWithChildren,
  }

const HelpCenterLayoutTopic_sectionRouteWithChildren =
  HelpCenterLayoutTopic_sectionRoute._addFileChildren(
    HelpCenterLayoutTopic_sectionRouteChildren,
  )

interface HelpCenterLayoutRouteChildren {
  HelpCenterLayoutIndexRoute: typeof HelpCenterLayoutIndexRoute
  HelpCenterLayoutActivitiesRoute: typeof HelpCenterLayoutActivitiesRouteWithChildren
  HelpCenterLayoutTopic_articleRoute: typeof HelpCenterLayoutTopic_articleRouteWithChildren
  HelpCenterLayoutTopic_categoryRoute: typeof HelpCenterLayoutTopic_categoryRouteWithChildren
  HelpCenterLayoutTopic_sectionRoute: typeof HelpCenterLayoutTopic_sectionRouteWithChildren
  HelpCenterLayoutSubmit_requestIndexRoute: typeof HelpCenterLayoutSubmit_requestIndexRoute
}

const HelpCenterLayoutRouteChildren: HelpCenterLayoutRouteChildren = {
  HelpCenterLayoutIndexRoute: HelpCenterLayoutIndexRoute,
  HelpCenterLayoutActivitiesRoute: HelpCenterLayoutActivitiesRouteWithChildren,
  HelpCenterLayoutTopic_articleRoute:
    HelpCenterLayoutTopic_articleRouteWithChildren,
  HelpCenterLayoutTopic_categoryRoute:
    HelpCenterLayoutTopic_categoryRouteWithChildren,
  HelpCenterLayoutTopic_sectionRoute:
    HelpCenterLayoutTopic_sectionRouteWithChildren,
  HelpCenterLayoutSubmit_requestIndexRoute:
    HelpCenterLayoutSubmit_requestIndexRoute,
}

const HelpCenterLayoutRouteWithChildren =
  HelpCenterLayoutRoute._addFileChildren(HelpCenterLayoutRouteChildren)

interface HelpCenterRouteChildren {
  HelpCenterLayoutRoute: typeof HelpCenterLayoutRouteWithChildren
}

const HelpCenterRouteChildren: HelpCenterRouteChildren = {
  HelpCenterLayoutRoute: HelpCenterLayoutRouteWithChildren,
}

const HelpCenterRouteWithChildren = HelpCenterRoute._addFileChildren(
  HelpCenterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpCenterRoute: HelpCenterRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  authSigninLazyRoute: authSigninLazyRoute,
  ContactDetailsIndexRoute: ContactDetailsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  CategoriesCategoryIdArticleIdRoute: CategoriesCategoryIdArticleIdRoute,
  CategoriesCategoryIdIndexRoute: CategoriesCategoryIdIndexRoute,
  ProtectedUserIndexRoute: ProtectedUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
